# Old: windowrule=workspace 5, title:Spotify Premium
windowrule = match:title Spotify Premium, workspace 5

# Old: windowrule=workspace 1, class:(obsidian)
windowrule = match:class obsidian, workspace 1

# Old: windowrule=workspace 2, class:(zen-beta)
windowrule = match:class zen-beta, workspace 2

# Old: windowrule=workspace 4, class:(dev.zed.Zed)
windowrule = match:class dev.zed.Zed, workspace 4

# Old: windowrule=workspace 1, class:(steam)
windowrule = match:class steam, workspace 1

# Old: windowrule=float, class:(org.pulseaudio.pavucontrol)
windowrule = match:class org.pulseaudio.pavucontrol, float on

# Old: windowrule=float, class:(org.gnome.Characters)
windowrule = match:class org.gnome.Characters, float on

# Old: windowrule=float, class:(xdg-desktop-portal-gtk)
windowrule = match:class xdg-desktop-portal-gtk, float on

# Old: windowrule=float, class:(org.gnome.Calculator)
windowrule = match:class org.gnome.Calculator, float on

# Old: windowrule=float, initialTitle:(Calendar Reminders)
windowrule = match:initial_title Calendar Reminders, float on

# Old: windowrule=float, title:^(Picture-in-Picture)$
windowrule = match:title ^Picture-in-Picture$, float on

# Old: windowrule=float, class:(org.kde.kdeconnect.app)
windowrule = match:class org.kde.kdeconnect.app, float on

# Old: windowrule=pin, title:^(Picture-in-Picture)$
windowrule = match:title ^Picture-in-Picture$, pin on

# Old: windowrule=move 69.5% 4%, title:^(Picture-in-Picture)$
windowrule = match:title ^Picture-in-Picture$, move 69.5% 4%

# Old: windowrule=fullscreen, class:(steam)
windowrule = match:class steam, fullscreen on

# Old: windowrule=float, class:(soffice)
windowrule = match:class soffice, float on

# Old: windowrule=float, initialTitle:(File Operation Progress)
windowrule = match:initial_title File Operation Progress, float on

# Old: windowrule=size 600 200, initialTitle:(File Operation Progress)
windowrule = match:initial_title File Operation Progress, size 600 200

# Old: windowrule=suppressevent maximize, class:.*
windowrule = match:class .*, suppress_event maximize

# Old: windowrule=size 1200 800, float,class:^(zen-beta)$,initialTitle:^(File Upload)$
windowrule = match:class ^zen-beta$ match:initial_title ^File Upload$ match:float yes, size 1200 800
