cursor #191d17
cursor_text_color #424940

foreground            #191d17
background            #f7fbf1
selection_foreground  #ffffff
selection_background  #4caf50
url_color             #2e7d32

color0   #10140f
color1   #79331d
color2   #125f11
color3   #998807
color4   #2c8330
color5   #b0ddb2
color6   #2e7d32
color7   #212321
color8   #686c69
color9   #a65b42
color10  #2c8c2a
color11  #a59513
color12  #2b8f30
color13  #b0ddb2
color14  #6fa271
color15  #babfba
