cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #3b2f15
selection_background  #d8c4a0
url_color             #f2bf48

color0   #131313
color1   #ff4a39
color2   #61f248
color3   #ffde39
color4   #e5ab24
color5   #704e00
color6   #f2bf48
color7   #fef7e8
color8   #9d988c
color9   #ff8378
color10  #94ff81
color11  #ffea81
color12  #ffd166
color13  #ffd981
color14  #ffe6ae
color15  #fffcf6
