cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #1b3435
selection_background  #b0cccc
url_color             #4cdadc

color0   #131313
color1   #fd4688
color2   #4cdc58
color3   #fff147
color4   #2cced1
color5   #006465
color6   #4cdadc
color7   #d4e6e7
color8   #808e8f
color9   #ff81ae
color10  #8aff93
color11  #fff68a
color12  #6bf0f2
color13  #8afdff
color14  #b3fdff
color15  #f6feff
